### ISSUE TITLE
egencache --repo=spring --update-use-local-desc fails

### ISSUE THREAD

**Issue by nado** [springlobby/overlay#30]
Hi,

`egencache --repo=spring --update-use-local-desc `
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.6/egencache", line 1120, in <module>
    sys.exit(egencache_main(sys.argv[1:]))
  File "/usr/lib/python-exec/python3.6/egencache", line 1067, in egencache_main
    gen_desc.run()
  File "/usr/lib/python-exec/python3.6/egencache", line 602, in run
    target=_MetadataTreeBuilder()))
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 1196, in parse
    tree.parse(source, parser)
  File "/usr/lib64/python3.6/xml/etree/ElementTree.py", line 603, in parse
    parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 6, column 60
```

I think this is the related error from repoman.
```
metadata.bad [fatal]          1
   games-util/flobby/metadata.xml: xmlParseEntityRef: no name, line 6, column 61 (metadata.xml, line 6)
```

**Comment by mfld-fr** [comment]
Waiting for @specing's response to https://github.com/springlobby/overlay/issues/25#issuecomment-998125125 before submitting an update to `metadata.xml`...
