### ISSUE TITLE
[spring] Build fails on generating 'spring-opengl4' man page

### ISSUE THREAD

**Issue by mfld-fr** [springlobby/overlay#41]
Trying to build on latest 'master' branch that is now 106.0.

The build fails here:
```
[884/1432] cd /mnt/data/var/tmp/portage/games-strategy/spring-9999/work/spring-9999/doc/manpages && /mnt/data/var/tmp/portage/games-
strategy/spring-9999/work/spring-9999/doc/manpages/make_manpages.sh /mnt/data/var/tmp/portage/games-strategy/spring-9999/work/spring
-9999_build/manpages /usr/bin/asciidoc /usr/bin/xsltproc /usr/share/sgml/docbook/xsl-stylesheets/manpages/docbook.xsl /usr/bin/7z
Note: Writing spring.6
asciidoc: ERROR: <stdin>: line 12: malformed name section body
asciidoc: ERROR: <stdin>: line 15: malformed name section body
asciidoc: FAILED: <stdin>: line 15: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/asciidoc", line 6220, in asciidoc
    document.translate(has_header)  # Generate the output.
  File "/usr/bin/asciidoc", line 1615, in translate
    self.attributes['manname'] = mo.group('manname').strip()
AttributeError: 'NoneType' object has no attribute 'group'
asciidoc: ERROR: <stdin>: line 12: malformed name section body
asciidoc: ERROR: <stdin>: line 15: malformed name section body
asciidoc: FAILED: <stdin>: line 15: unexpected error:
asciidoc: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/asciidoc", line 6220, in asciidoc
    document.translate(has_header)  # Generate the output.
  File "/usr/bin/asciidoc", line 1615, in translate
    self.attributes['manname'] = mo.group('manname').strip()
AttributeError: 'NoneType' object has no attribute 'group'
sed: can't read /mnt/data/var/tmp/portage/games-strategy/spring-9999/work/spring-9999_build/manpages/spring-opengl4.6.xml: No such file or directory
/mnt/data/var/tmp/portage/games-strategy/spring-9999/work/spring-9999_build/manpages/spring-opengl4.6.xml:1: parser error : Document is empty

^
unable to parse /mnt/data/var/tmp/portage/games-strategy/spring-9999/work/spring-9999_build/manpages/spring-opengl4.6.xml

WARNING: No more files
/mnt/data/var/tmp/portage/games-strategy/spring-9999/work/spring-9999_build/manpages/spring-opengl4.6



System ERROR:
E_INVALIDARG
Note: Writing spring-headless.6
Note: Writing spring-dedicated.6
```

**Comment by abma** [comment]
thanks for reporting!

should be fixed by https://github.com/spring/spring/commit/553a21526b144568b608a0507674b076ec80d9f9
